# Generated by Django 3.0.4 on 2020-07-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
